In [2]:
import numba
from numba import cuda

In [3]:
import cupy
import numpy as np
import math
import time
import numba
from numba import cuda
from numba import njit
from numba import prange
import cudf
cupy.cuda.set_allocator(None)
#110.0, 100.0, 120.0, 0.35, 0.1, 0.05
N_PATHS = 8192000
Y_STEPS = 365 # constant, number of steps per year
T = 1.0 # time, unit 1 year
K = 110.0 # Strike price
B = 100.0 # barrier price
S0 = 120.0 # initial stock price 
sigma = 0.35 # stock annual volatility 
mu = 0.1 # stock annual return
r = 0.05 # stock annual interest rate
# calculate total step size
N_STEPS = int(np.ceil(T * Y_STEPS))
print('steps', N_STEPS)

steps 365


In [4]:
cupy.random.seed(11)

In [5]:
randoms_gpu = cupy.random.normal(0, 1, N_PATHS * N_STEPS, dtype=cupy.float32)
# randoms_cpu = np_randoms = cupy.asnumpy(randoms_gpu)
output =  np.zeros(N_PATHS, dtype=np.float32)

doutput =  np.zeros(N_PATHS*6, dtype=np.float32)

In [6]:
@cuda.jit
def numba_gpu_barrier_option(d_s, T, K, B, S0, sigma, mu, r, d_normals, N_STEPS, N_PATHS):
    # ii - overall thread index
    
    ii = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x
    stride = cuda.gridDim.x * cuda.blockDim.x
    tmp1 = mu/Y_STEPS
    tmp2 = math.exp(-r*T)
    tmp3 = math.sqrt(1.0/Y_STEPS)
    running_average = 0.0
    for i in range(ii, N_PATHS, stride):
        s_curr = S0
        for n in range(N_STEPS):
            if n == N_STEPS - 1:
                delta_t = T - n/Y_STEPS
                tmp1 = delta_t * mu
                tmp3 = math.sqrt(delta_t)                
            s_curr += tmp1 * s_curr + sigma*s_curr*tmp3*d_normals[i + n * N_PATHS]
            running_average += (s_curr - running_average) / (n + 1.0)
            # print(running_average, n, tmp1 * s_curr, sigma,s_curr, tmp3,d_normals[i + n * N_PATHS])
            if running_average <= B:
                break
        payoff = running_average - K if running_average>K else 0
        d_s[i] = tmp2 * payoff

In [7]:
number_of_threads = 256
number_of_blocks = (N_PATHS-1) // number_of_threads + 1
output = cupy.zeros(N_PATHS, dtype=cupy.float32)
numba_gpu_barrier_option[(number_of_blocks,), (number_of_threads,)](output, np.float32(T), np.float32(K), 
                    np.float32(B), np.float32(S0), 
                    np.float32(sigma), np.float32(mu), 
                    np.float32(r), randoms_gpu, N_STEPS, N_PATHS)
s = time.time()
numba_gpu_barrier_option[(number_of_blocks,), (number_of_threads,)](output, np.float32(T), np.float32(K), 
                    np.float32(B), np.float32(S0), 
                    np.float32(sigma), np.float32(mu), 
                    np.float32(r), randoms_gpu, N_STEPS, N_PATHS)
v = output.mean()
cuda.synchronize()
e = time.time()
print('time', e-s, 'v', v)

time 0.448864221572876 v 18.708305


In [8]:
(19.43269 - 19.432878)/2e-4





-0.9399999999892827

In [9]:
1/365

0.0027397260273972603

In [10]:
output

array([59.287468  ,  0.9394655 ,  4.4536147 , ...,  0.67556167,
       10.877099  ,  0.52545613], dtype=float32)

Calculate the differentiation by ADD method

The parameters are $T$, $K$, $S_0$, $\sigma$, $\mu$, $r$. The option price is computed by 
$$ p = E(f_i(\theta)) = \frac{1}{N}\sum_i f_i$$
where $f_i$ is the option value at the exercise time for the $i^{th}$ path.
$$\nabla_{\theta} p = \frac{1}{N}\sum_i \nabla_{\theta} f_i $$

Let's focus on the calculation of gradient of $f_i(\theta)$. $f_i$ is calculated by Monte Carlo simulation method. Break it down into steps. Without loss of generality, we drop the index $i$ here.

$$    \nabla_{\theta} f = 
\begin{cases}
    \nabla_{\theta} (a_n(\theta) - K)  & \text{if } a_n\geq K\\
    (0,0,0,0,0,0)              & \text{otherwise}
\end{cases}
$$

where the moving average $a_n$ at step $n$ is

$$a_n = g(a_{n-1}, s_{n}) = a_{n-1} + \frac{s_{n} - a_{n-1}}{n + 1.0}$$

The gradient of $a_n$:
$$ \nabla_{\theta} a_n = \frac{\partial g} {\partial a_{n-1}} \nabla_{\theta} a_{n-1} + \frac{\partial g} {\partial s_{n}} \nabla_{\theta} s_{n} = \frac{n}{n+1} \nabla_{\theta} a_{n-1} + \frac{1}{n+1} \nabla_{\theta} s_{n} $$

The stock price $s_n$ at step $n$ is:
$$s_n = s(s_{n-1}, \theta) = s_{n-1} + \frac{\mu}{Y} s_{n-1} + \sigma  \sqrt{\frac{1}{Y}} n_n s_{n-1}$$
At the last time step $s_n$ is:
$$s_n = s(s_{n-1}, \theta) = s_{n-1} + \frac{\mu (T Y - n) }{Y} s_{n-1} + \sigma  \sqrt{\frac{TY-n}{Y}} n_n s_{n-1}$$
The gradient of $s_n$:
$$\nabla_{\theta} s_n = \nabla_{\theta} s(s_{n-1}, \theta) = (1 + \frac{\mu}{Y} + \sigma \sqrt{\frac{1}{Y}} n_n) \nabla_{\theta} s_{n-1} + \nabla_{\theta} (1 + \frac{\mu}{Y} + \sigma \sqrt{\frac{1}{Y}} n_n) s_{n-1} $$

The initial contition $$\nabla_{\theta} S_0 = (0,0,1,0,0,0)$$

$$\nabla_{\theta} (1 + \frac{\mu}{Y} + \sigma \sqrt{\frac{1}{Y}} v_n) = (0, 0, 0, 1/Y, \sqrt{1/Y} n_n ,0) $$

$$\nabla_{\theta} (\frac{1+ \mu (T Y - n) }{Y} + \sigma  \sqrt{\frac{TY-n}{Y}} n_n ) = (\mu + \frac{1}{2}\sigma n_n (T-n/Y)^{-\frac{1}{2}}, 0, 0, (T-n/Y), \sqrt{T-n/Y} n_n ,0) $$

In [11]:
@cuda.jit
def numba_gpu_barrier_option(d_s, doutput, T, K, B, S0, sigma, mu, r, d_normals, N_STEPS, N_PATHS):
    # ii - overall thread index
    
    ii = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x
    stride = cuda.gridDim.x * cuda.blockDim.x
    tmp1 = mu/Y_STEPS
    tmp2 = math.exp(-r*T)
    tmp3 = math.sqrt(1.0/Y_STEPS)
    running_average = 0.0
    d_theta = numba.cuda.local.array(6, numba.float64)
    d_a = numba.cuda.local.array(6, numba.float64)
    for i in range(ii, N_PATHS, stride):
        d_theta[0] = 0 # T
        d_theta[1] = 0 # K
        d_theta[2] = 1 # S_0
        d_theta[3] = 0 # mu
        d_theta[4] = 0 # sigma
        d_theta[5] = 0 # r
        for k in range(6):
            d_a[k] = 0
        s_curr = S0
        for n in range(N_STEPS):
            if n == N_STEPS - 1:
                delta_t = T - n/Y_STEPS
                tmp1 = delta_t * mu
                tmp3 = math.sqrt(delta_t)  
            
            ## start to compute the gradient
            factor = (1.0+tmp1+sigma*tmp3*d_normals[i + n * N_PATHS])
            for k in range(6):
                 d_theta[k] *= factor
            if n == N_STEPS - 1:
                d_theta[0] += (mu + 0.5 * sigma * d_normals[i + n * N_PATHS] / tmp3) * s_curr
                d_theta[3] += (T - n/Y_STEPS) * s_curr
                d_theta[4] += tmp3 * d_normals[i + n * N_PATHS] * s_curr
            else:
                d_theta[3] += 1.0/Y_STEPS * s_curr
                d_theta[4] += tmp3 * d_normals[i + n * N_PATHS] * s_curr
            for k in range(6):
                d_a[k] = d_a[k]*n/(n+1.0) + d_theta[k]/(n+1.0)
            ## start to compute current stock price and moving average
              
            s_curr += tmp1 * s_curr + sigma*s_curr*tmp3*d_normals[i + n * N_PATHS]
            running_average += (s_curr - running_average) / (n + 1.0)
            # print(running_average, n, tmp1 * s_curr, sigma,s_curr, tmp3,d_normals[i + n * N_PATHS])
            if running_average <= B:
                break
        payoff = running_average - K if running_average>K else 0
        d_s[i] = tmp2 * payoff
        # gradient for strik 
        if running_average > K:
            d_a[1] = -1
            # adjust gradient for discount factor
            for k in range(6):
                d_a[k] *= tmp2
            d_a[0] += payoff * tmp2* -r 
            d_a[5] += payoff * tmp2* -T
        else:
            for k in range(6):
                d_a[k] = 0
        for k in range(6):
            doutput[k*N_PATHS+i] = d_a[k]

In [12]:
number_of_threads = 256
number_of_blocks = (N_PATHS-1) // number_of_threads + 1
output = cupy.zeros(N_PATHS, dtype=cupy.float32)
numba_gpu_barrier_option[(number_of_blocks,), (number_of_threads,)](output, doutput, np.float32(T), np.float32(K), 
                    np.float32(B), np.float32(S0), 
                    np.float32(sigma), np.float32(mu), 
                    np.float32(r), randoms_gpu, N_STEPS, N_PATHS)
s = time.time()
numba_gpu_barrier_option[(number_of_blocks,), (number_of_threads,)](output, doutput, np.float32(T), np.float32(K), 
                    np.float32(B), np.float32(S0), 
                    np.float32(sigma), np.float32(mu), 
                    np.float32(r), randoms_gpu, N_STEPS, N_PATHS)
v = output.mean()
cuda.synchronize()
e = time.time()
print('time', e-s, 'v', v)
greeks = doutput.reshape(6, N_PATHS).mean(axis=1)
print('greeks', greeks)

time 1.846067190170288 v 18.708305
greeks [ -0.9074474  -0.6714072   0.7713591  48.02249    20.488997  -18.708313 ]


In [291]:
import cupy
cupy_batched_barrier_option = cupy.RawKernel(r'''
extern "C" __global__ void batched_barrier_option(
    float *d_s,
    float *d_d,
    const float * T,
    const float * K,
    const float * B,
    const float * S0,
    const float * sigma,
    const float * mu,
    const float * r,
    const float * d_normals,
    const long *N_STEPS,
    const long Y_STEPS,
    const long N_PATHS,
    const long N_BATCH)
{
  unsigned idx =  threadIdx.x + blockIdx.x * blockDim.x;
  unsigned stride = blockDim.x * gridDim.x;
  unsigned tid = threadIdx.x;
  double d_theta[6];
  double d_a[6];

  for (unsigned i = idx; i<N_PATHS * N_BATCH; i+=stride)
  {
    d_theta[0] = 0; // T
    d_theta[1] = 0; // K
    d_theta[2] = 1.0; // S_0
    d_theta[3] = 0; // mu
    d_theta[4] = 0; // sigma
    d_theta[5] = 0; // r
    for (unsigned k = 0; k < 6; k++){
      d_a[k] = 0.0;
    }
    
    int batch_id = i / N_PATHS;
    int path_id = i % N_PATHS;
    float s_curr = S0[batch_id];
    float tmp1 = mu[batch_id]/Y_STEPS;
    float tmp2 = exp(-r[batch_id]*T[batch_id]);
    float tmp3 = sqrt(1.0/Y_STEPS);
    unsigned n=0;
    double running_average = 0.0;
    for(unsigned n = 0; n < N_STEPS[batch_id]; n++){
        if (n == N_STEPS[batch_id] - 1) {
            float delta_t = T[batch_id] - n/Y_STEPS;
            tmp1 = delta_t * mu[batch_id];
            tmp3 = sqrt(abs(delta_t));
        }
        float normal = d_normals[path_id + batch_id * N_PATHS + n * N_PATHS * N_BATCH];
        
            
        // start to compute the gradient
        float factor = (1.0+tmp1+sigma[batch_id]*tmp3*normal);
        for (unsigned k=0; k < 6; k++) {
            d_theta[k] *= factor;
        }
        
        if (n == N_STEPS[batch_id] - 1){
                d_theta[0] += (mu[batch_id] + 0.5 * sigma[batch_id] * normal / tmp3) * s_curr;
                d_theta[3] += (T[batch_id] - n/Y_STEPS) * s_curr;
                d_theta[4] += tmp3 * normal * s_curr;
        }
        else {
                d_theta[3] += 1.0/Y_STEPS * s_curr;
                d_theta[4] += tmp3 * normal * s_curr;
        }
        for (unsigned k = 0; k < 6; k++) {
                d_a[k] = d_a[k]*n/(n+1.0) + d_theta[k]/(n+1.0); 
        }
        
        
        // start to compute current stock price and moving average       
       
       s_curr += tmp1 * s_curr + sigma[batch_id]*s_curr*tmp3*normal;
       running_average += (s_curr - running_average) / (n + 1.0);
       if (running_average <= B[batch_id]){
           break;
       }
    }

    float payoff = (running_average>K[batch_id] ? running_average-K[batch_id] : 0.f); 
    d_s[i] = tmp2 * payoff;
    //printf("%d, %d, %f, %f, %f, %d\n", i, idx, d_s[i], payoff, K[batch_id], batch_id);
    
    // gradient for strik 
    if (running_average > K[batch_id]){
       d_a[1] = -1.0;
       // adjust gradient for discount factor
       for (unsigned k = 0; k < 6; k++) {
            d_a[k] *= tmp2;
        }
        d_a[0] += payoff * tmp2* -r[batch_id];
        d_a[5] += payoff * tmp2* -T[batch_id];
        
    }
    else {
        for (unsigned k = 0; k < 6; k++) {
           d_a[k] = 0.0;
        }

    }
    
    for (unsigned k = 0; k < 6; k++) {
       d_d[k*N_PATHS*N_BATCH+i] = d_a[k];
    }
  }
}

''', 'batched_barrier_option')

In [292]:

import numpy
cupy.ceil((cupy.random.rand(10)*5)).astype(cupy.int64)

array([2, 4, 5, 2, 1, 4, 3, 2, 5, 5])

In [293]:
Y_STEPS = 252
N_BATCH = 2
N_PATHS = 102400
#N_PATHS = 1
#110.0, 100.0, 120.0, 0.35, 0.1, 0.05
K = cupy.array([110.0, 120.0], dtype=cupy.float32)
B = cupy.array([100.0, 90.0], dtype=cupy.float32)
S0 = cupy.array([120.0, 100.0], dtype=cupy.float32)
sigma = cupy.array([0.35, 0.2], dtype=cupy.float32)
mu = cupy.array([0.1, 0.1], dtype=cupy.float32)
r =cupy.array([0.05, 0.05], dtype=cupy.float32)
T =cupy.array([1.0, 1.1], dtype=cupy.float32)
N_STEPS = cupy.ceil(T * Y_STEPS).astype(cupy.int64)

In [294]:
N_STEPS

array([252, 278])

In [296]:
import time
def batch_run():
    number_of_threads = 256
    number_of_blocks = (N_PATHS * N_BATCH - 1) // number_of_threads + 1
    random_elements = (N_STEPS.max()*N_PATHS*N_BATCH).item()
    randoms_gpu = cupy.random.normal(0, 1, random_elements, dtype=cupy.float32)
    output = cupy.zeros(N_BATCH*N_PATHS, dtype=cupy.float32)
    d_output = cupy.zeros(N_BATCH*N_PATHS*6, dtype=cupy.float32)
    cupy.cuda.stream.get_current_stream().synchronize()
    s = time.time() 
    cupy_batched_barrier_option((number_of_blocks,), (number_of_threads,),
                       (output, d_output, T, K, B, S0, sigma, mu, r,
                        randoms_gpu, N_STEPS, Y_STEPS, N_PATHS, N_BATCH))
    v = output.reshape(N_BATCH, N_PATHS).mean(axis=1)
    b = d_output.reshape(6, N_BATCH, N_PATHS).mean(axis=2)
    cupy.cuda.stream.get_current_stream().synchronize()
    e = time.time()
    print('time', e-s, 'v',v)
    print(b.shape)
    print('gradient', b)
    return output
o = batch_run()

time 0.04712033271789551 v [18.79062    1.0715227]
(6, 2)
gradient [[-8.9936632e-01 -4.6629854e-02]
 [-6.7166764e-01 -1.3070557e-01]
 [ 7.7228278e-01  1.6756187e-01]
 [ 4.8548283e+01  9.8501930e+00]
 [ 2.0610815e+01  1.5758758e+01]
 [-1.8790621e+01 -1.1786751e+00]]


In [297]:
[1.  1.1]
[110. 120.]
[100.  90.]
[120. 100.]
[0.35 0.2 ]
[0.1 0.1]
[0.05 0.05]
[252 278]
102400
2
252

SyntaxError: invalid syntax (<ipython-input-297-c14c7a2ec9fd>, line 1)

In [298]:
o = batch_run()

time 0.046544551849365234 v [18.61465   1.056389]
(6, 2)
gradient [[-8.9069074e-01 -4.5857679e-02]
 [-6.7100799e-01 -1.2942077e-01]
 [ 7.7021182e-01  1.6586880e-01]
 [ 4.8381561e+01  9.7541447e+00]
 [ 2.0081079e+01  1.5582058e+01]
 [-1.8614651e+01 -1.1620281e+00]]


In [317]:
class ParameterIter(object):
    
    def __init__(self, batch, K=200.0, S0=200.0, sigma=0.4, mu=0.2, r=0.2, T=1.9, minT=0.1):
        self.N_BATCH = batch
        self.K = K
        self.S0 = S0
        self.sigma = sigma
        self.mu = mu
        self.r = r
        self.T = T
        self.minT = minT
        
    def __iter__(self):
        return self
        
        
    def __next__(self):
        X = cupy.random.rand(self.N_BATCH, 7, dtype=cupy.float32)
        # scale the [0, 1) random numbers to the correct range for each of the option parameters
        X = X * cupy.array([ 0.99, self.K, self.S0, self.sigma, self.mu, self.r, self.T], dtype=cupy.float32)
        # make sure the Barrier is smaller than the Strike price
        X[:, 0] = X[:, 0] * X[:, 1]
        X[:, 6] += self.minT 
        
        X[:, 0] += 10.0
        X[:, 1] += 10.0        
        X[:, 2] += 10.0  
        
        X[:, 5] += 0.0001
        X[:, 4] += 0.0001
        X[:, 3] += 0.0001
        return X

In [318]:
        K = cupy.array([110.0, 120.0], dtype=cupy.float32)[:, None]
        B = cupy.array([100.0, 90.0], dtype=cupy.float32)[:, None]
        S0 = cupy.array([120.0, 100.0], dtype=cupy.float32)[:, None]
        sigma = cupy.array([0.35, 0.2], dtype=cupy.float32)[:, None]
        mu = cupy.array([0.1, 0.1], dtype=cupy.float32)[:, None]
        r =cupy.array([0.05, 0.05], dtype=cupy.float32)[:, None]
        T =cupy.array([1.0, 1.1], dtype=cupy.float32)[:, None]
        X = cupy.concatenate([B, K, S0, sigma, mu, r, T], axis=1)

In [319]:
X[:, 2]

array([120., 100.], dtype=float32)

In [321]:
class SimulationIter(object):
    
    def __init__(self, para_iter, N_PATHS=102400, Y_STEPS=252):
        self.para_iter = para_iter
        self.N_PATHS = N_PATHS
        self.Y_STEPS = Y_STEPS
        self.N_BATCH = para_iter.N_BATCH
        self.block_threads = 256
    
    def __iter__(self):
        return self
    
    def __next__(self):
        para = next(self.para_iter)
        B = cupy.ascontiguousarray(para[:, 0])
        K = cupy.ascontiguousarray(para[:, 1])
        S0 = cupy.ascontiguousarray(para[:, 2])
        sigma = cupy.ascontiguousarray(para[:, 3])
        mu = cupy.ascontiguousarray(para[:, 4])
        r = cupy.ascontiguousarray(para[:, 5])
        T = cupy.ascontiguousarray(para[:, 6])
        N_STEPS = cupy.ceil(T * self.Y_STEPS).astype(cupy.int64)
        number_of_threads = self.block_threads
        number_of_blocks = (self.N_PATHS * self.N_BATCH - 1) // number_of_threads + 1
        random_elements = (N_STEPS.max()*self.N_PATHS*self.N_BATCH).item()
        randoms_gpu = cupy.random.normal(0, 1, random_elements, dtype=cupy.float32)
        output = cupy.zeros(self.N_BATCH * self.N_PATHS, dtype=cupy.float32)
        d_output = cupy.zeros(self.N_BATCH*self.N_PATHS*6, dtype=cupy.float32)
        cupy_batched_barrier_option((number_of_blocks,), (number_of_threads,),
                                    (output, d_output, T, K, B, S0, sigma, mu, r,
                                    randoms_gpu, N_STEPS, self.Y_STEPS, self.N_PATHS, self.N_BATCH))
        v = output.reshape(self.N_BATCH, self.N_PATHS).mean(axis=1)[:,None]
        b = d_output.reshape(6, self.N_BATCH, self.N_PATHS).mean(axis=2).T
        print(v, b, 'batch', self.N_BATCH)
        y = cupy.concatenate([v, b], axis=1)
        return para, y

In [325]:
import torch
from torch.utils.dlpack import from_dlpack
class OptionDataSet(torch.utils.data.IterableDataset):
    
    def __init__(self, sim_iter,  max_len=10):
        self.sim_iter = sim_iter
        self.num = 0
        self.max_length = max_len
        
    def __len__(self):
        return self.max_length
        
    def __iter__(self):
        self.num = 0
        return self
    
    def __next__(self):
        if self.num > self.max_length:
            raise StopIteration
        X, Y = next(self.sim_iter)
        return (from_dlpack(X.toDlpack()), from_dlpack(Y.toDlpack()))

In [329]:
it = ParameterIter(16)
sit = SimulationIter(it, N_PATHS=102400)
tit = OptionDataSet(sit, 3)

In [331]:
r = next(tit)


[[9.95539246e+01]
 [5.44735565e+01]
 [4.61282043e+01]
 [2.42577896e-01]
 [0.00000000e+00]
 [1.25134885e+00]
 [9.22882156e+01]
 [1.01847061e+02]
 [4.11675301e+01]
 [9.10452423e+01]
 [2.61180668e+01]
 [0.00000000e+00]
 [1.00481985e-02]
 [0.00000000e+00]
 [3.78219490e+01]
 [1.92463485e-05]] [[-3.4878976e+00 -9.6089178e-01  9.6884519e-01  9.9972366e+01
   3.4807563e-01 -1.1308288e+02]
 [-6.6788596e-01 -9.5906717e-01  9.8566139e-01  7.0233406e+01
   4.4074111e+00 -4.1361664e+01]
 [-1.2795538e+00 -9.6609879e-01  9.8898524e-01  7.1394981e+01
   8.9391097e-02 -5.6724735e+01]
 [-2.7836058e-02 -2.7924962e-02  4.3223362e-02  2.3257334e+00
   4.9027953e+00 -2.9349783e-01]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00
   0.0000000e+00  0.0000000e+00]
 [-1.1430586e-01 -1.0131233e-01  1.4563225e-01  1.5086294e+01
   1.9643900e+01 -2.1316977e+00]
 [-1.1388243e+00 -9.9046427e-01  1.0425670e+00  6.3266953e+01
   3.4120589e-01 -6.2872139e+01]
 [-1.6735237e+01 -7.9286802e-01  8.5623991e-01

In [286]:
cupy.ascontiguousarray(r[0][:,0])

array([100.,  90.], dtype=float32)

In [98]:
r[1].shape

(2, 7)

In [16]:
r[0][:,6]

array([2.0536091 , 1.0843736 , 0.30162492, 1.8862414 , 1.9676563 ,
       0.6779451 , 1.7747545 , 0.12224215], dtype=float32)

In [58]:
from gquant.dataframe_flow import Node
from gquant.dataframe_flow import NodePorts, PortsSpecSchema, TaskSpecSchema
from gquant.dataframe_flow import ConfSchema
from gquant.dataframe_flow import TaskGraph

In [59]:
class ParaNode(Node):

    def ports_setup(self):
        input_ports = {}
        output_ports = {
            'para_out': {
                PortsSpecSchema.port_type: ParameterIter
            },
        }
        return NodePorts(inports=input_ports, outports=output_ports)

    def conf_schema(self):
        json = {
            "title": "Source node configure",
            "type": "object",
            "properties": {
                "batch": {
                    "type": "integer",
                    "title": "batch size",
                    "description": "the batch size for Asian Barrier Option parameters",
                    "default": 16
                }
            }
        }
        ui = {}
        return ConfSchema(json=json, ui=ui)

    def init(self):
        self.required = {}

    def columns_setup(self):
        columns_out = {
            'para_out': {
                'B': 'float32',
                'K': 'float32',
                "S0": "float32",
                "sigma": "float32",
                "mu": "float32",
                "r": "float32",
                "T": "float32"
            },
        }
        return columns_out

    def process(self, inputs):
        output = {}
        it = ParameterIter(self.conf.get('batch', 16))
        output.update({'para_out': it})
        return output

In [65]:
class SimNode(Node):

    def ports_setup(self):
        input_ports = {
             'para_in': {
                PortsSpecSchema.port_type: ParameterIter
            },           
        }
        output_ports = {
            'sim_out': {
                PortsSpecSchema.port_type: SimulationIter
            },
        }
        return NodePorts(inports=input_ports, outports=output_ports)

    def conf_schema(self):
        json = {
            "title": "Monte Carlo Sim node configure",
            "type": "object",
            "properties": {
                "N_PATHS": {
                    "type": "integer",
                    "title": "Number Paths",
                    "description": "Number of paths in the simulation",
                    "default": 102400
                },
                "Y_STEPS": {
                    "type": "integer",
                    "title": "Steps per year",
                    "description": "Number of steps for one year",
                    "default": 252
                },
            }
        }
        ui = {}
        return ConfSchema(json=json, ui=ui)

    def init(self):
        self.required = {}

    def columns_setup(self):
        self.requried = {
            "para_in": {
                'B': 'float32',
                'K': 'float32',
                "S0": "float32",
                "sigma": "float32",
                "mu": "float32",
                "r": "float32",
                "T": "float32"
            },
        }
        columns_out = {
            'sim_out': {
                'X': 'parameters',
                'Y': 'values'
            },
        }
        return columns_out

    def process(self, inputs):
        it = inputs['para_in']
        sit = SimulationIter(it, N_PATHS=self.conf.get('N_PATHS', 102400), Y_STEPS=self.conf.get('Y_STEPS', 252))
        output = {}
        output.update({'sim_out': sit})
        return output


In [66]:
module_name = 'option_pricing'
TaskGraph.register_lab_node(module_name, ParaNode)
TaskGraph.register_lab_node(module_name, SimNode)

In [67]:
taskGraph = TaskGraph()
taskGraph.draw()

GQuantWidget(sub=HBox())

In [68]:
next(taskGraph.run()[0])

IndexError: tuple index out of range

In [18]:
[ -0.9074474,  -0.6714072   0.7713591  48.02249    20.488997  -18.708313 ]

SyntaxError: invalid syntax (<ipython-input-18-9f78a3372395>, line 1)